### PR TITLE
Fixed compiler warnings

### LINKED ISSUE #2347: New warning in ACE
Get this new warning with current master, probably introduced by https://github.com/DOCGroup/ACE_TAO/pull/2339

```
/home/johnny/ACE/trunk/ACE/ace/Svc_Conf_y.cpp: In function ‘int ace_yyparse(void*)’:
/home/johnny/ACE/trunk/ACE/ace/Svc_Conf_y.cpp:1615:22: warning: ‘void free(void*)’ called on unallocated object ‘ace_yyssa’ [-Wfree-nonheap-object]
 1615 |     ACE_YYSTACK_FREE (ace_yyss);
      |                      ^
/home/johnny/ACE/trunk/ACE/ace/Svc_Conf_y.cpp:966:20: note: declared here
  966 |     ace_yy_state_t ace_yyssa[ACE_YYINITDEPTH];
      |                    ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by mitza-oci**
Follow-on to #2339
Fixes #2347 

## Summary by CodeRabbit

- **Chores**
  - Improved the build process by adding new build targets and updating the required version of Bison.

- **Refactor**
  - Streamlined internal object construction by removing unnecessary copy mechanisms, enhancing resource management and overall code safety.
  - Updated command line formatting in testing to ensure consistent process handling.
  - Simplified class definitions by utilizing default member functions for constructors and destructors.
  - Enhanced compiler warning management by adding directives for better compatibility with different compilers.
  - Improved option parsing logic for clarity and maintainability in the `TAO_SHMIOP_Acceptor` class.

### CODE REVIEW

File: TAO/tao/Valuetype/ValueBase.h [hunk 1]
```diff
@@ -335,11 +335,11 @@ namespace CORBA
 
   protected:
     DefaultValueRefCountBase ();
-    DefaultValueRefCountBase (const DefaultValueRefCountBase&);
+    DefaultValueRefCountBase (const DefaultValueRefCountBase &) = delete;
     virtual ~DefaultValueRefCountBase ();
 
   private:
-    void operator= (const DefaultValueRefCountBase &);
+    DefaultValueRefCountBase &operator= (const DefaultValueRefCountBase &) = delete;
```
Comment (jwillemsen) [inline TAO/tao/Valuetype/ValueBase.h:342]: I think these also need to be here, but these operators are not explicitly mentioned in the IDL to C++ spec

File: ACE/ace/Svc_Conf.y [hunk 2]
```diff
@@ -44,6 +44,11 @@ static ACE_Module_Type *
 #pragma warning(disable:4702)
 #endif
 
+#ifdef __GNUC__
```
Comment (jwillemsen) [inline ACE/ace/Svc_Conf.y:47]: Maybe add a comment why it is here so that we know it for the future

File: TAO/tao/PortableServer/Servant_Base.h [hunk 3]
```diff
@@ -184,13 +184,11 @@ class TAO_PortableServer_Export TAO_ServantBase
 
 protected:
   /// Default constructor, only derived classes can be created.
-  explicit TAO_ServantBase (TAO_Operation_Table* optable = 0);
+  explicit TAO_ServantBase (TAO_Operation_Table *optable = nullptr);
 
-  /// Copy constructor, protected so no instances can be created.
-  TAO_ServantBase (const TAO_ServantBase &);
```
[the remark this answers is not in the document]
Comment (mitza-oci) [reply TAO/tao/PortableServer/Servant_Base.h:190]: That seems like a bad idea, but you're right that we need to support it.  So we will need a real solution to the GCC invalid warning.

I guess it's a moot point, but could you have a copyable servant that doesn't copy its TAO_ServantBase base class subobject?

File: TAO/tao/Valuetype/ValueBase.h (hunk 1 above)
Comment (mitza-oci) [reply TAO/tao/Valuetype/ValueBase.h:342]: In this case the DefaultValueRefCountBase doesn't have to be derived by the application code, if it doesn't work for users they could use a different class.

**Comment by mitza-oci** [comment]
@jwillemsen here's the CodeQL problem I referenced earlier https://github.com/DOCGroup/ACE_TAO/pull/2350/checks?check_run_id=38572553836

**Review by iguessthislldo — APPROVED** [review]

**Comment by jwillemsen** [comment]
Strange, when I check https://github.com/DOCGroup/ACE_TAO/security/code-scanning/tools/CodeQL/status it does seem to work without problems

**Review by iguessthislldo — APPROVED** [review]

**Comment by jwillemsen** [comment]
New warnings on RHEL80, added a build again to the scoreboard.

**Comment by mitza-oci** [comment]
> New warnings on RHEL80, added a build again to the scoreboard.

Is this for the `DefaultValueRefCountBase` class?  I started some follow-on work for that one yesterday.

**Comment by jwillemsen** [comment]
Results are online again, see https://download.remedy.nl/buildlogs/rhel80_acetao_debug/

**Comment by jwillemsen** [comment]
Also new warnings in the OCI gcc builds on master

```
/var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/GNUmakefile.CC_client
[[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_103)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp: In member function 'virtual int CC_Start_Cmd::execute()':
[[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_104)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp:112:33: warning: format '%C' expects argument of type 'wint_t', but argument 3 has type 'char*' [-Wformat=]
[[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_105)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/ACE/ace/ace_wchar.h:97:27: note: in definition of macro 'ACE_TEXT'
[[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_106)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp:112:35: note: format string is defined here
```

**Comment by mitza-oci** [comment]
> Also new warnings in the OCI gcc builds on master
> 
> ```
> /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/GNUmakefile.CC_client
> [[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_103)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp: In member function 'virtual int CC_Start_Cmd::execute()':
> [[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_104)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp:112:33: warning: format '%C' expects argument of type 'wint_t', but argument 3 has type 'char*' [-Wformat=]
> [[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_105)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/ACE/ace/ace_wchar.h:97:27: note: in definition of macro 'ACE_TEXT'
> [[Details](https://storage.googleapis.com/oci-scoreboard/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/2025_03_14_09_24_Full.html#warning_106)] /var/lib/jenkins/workspace/ACE_TAO_Ubuntu_22_04_GCC14_x64_Debug/TAO/orbsvcs/tests/Concurrency/CC_command.cpp:112:35: note: format string is defined here
> ```

Yes, I'll fix it.  I confused logging formatters with printf formatters.

**Comment by mitza-oci** [comment]
> Yes, I'll fix it. I confused logging formatters with printf formatters.

Interesting (?) tangent here -- the `ACE_Process_Options::command_line()` overload that uses `...` doesn't seem like it can be used portably and wchar-correctly.  The meaning of `%s` formatting in the `*wprintf*` family of functions is different on Windows.

I think this needs to be avoided and the argv-style `command_line()` used in its place.

**Comment by mitza-oci** [comment]
> New warnings on RHEL80 `DefaultValueRefCountBase`
> Also new warnings in the OCI gcc builds on master

Fixing both in #2360
